version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      # checkout code, install node packages, install aws & eb cli
      - checkout
      - node/install
      - aws-cli/setup
      - eb/setup
      # Use root level package.json to install dependencies.
      - run:
          name: Install Dependencies.
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm install
      # TODO: Build the Store Front API      
      - run:
          name: API Build
          command: |
            echo "TODO: Build the Store Front API"
            npm run build
      # TODO: Build the API
      - run:
          name: API Deploy
          command: |
            echo "TODO: Build the Store Front API"
            npm run deploy